name: CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            fail-fast: false
            matrix:
              cxx: [g++-8, clang++]
        env:
          CXX: ${{ matrix.cxx }}
            
        steps:
        - uses: actions/checkout@v2
          with:
            submodules: true
        - name: Install Dependencies
          run: |
            ./installDependencies.sh
        - name: Set up Build
          run: |
            mkdir build
            cd build
            cmake ..
        - name: Build
          run: |
            cd build
            make
        - name: Install
          run: |
            cd build
            sudo make install
            
    googletest:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            fail-fast: false
            matrix:
              cxx: [g++-8, clang++]
        env:
          CXX: ${{ matrix.cxx }}
            
        steps:
        - uses: actions/checkout@v2
          with:
            submodules: true
        - name: Install Dependencies
          run: |
            ./installDependencies.sh
        - name: Set up Build
          run: |
            mkdir build
            cd build
            cmake ..
        - name: Build
          run: |
            cd build
            make
        - name: Tests
          run: |
            cd build
            ./test/LibCommon_test
            
    cpplint:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            fail-fast: false

        steps:
        - uses: actions/checkout@v1
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-verion: 3.7
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install cpplint
        - name: Code Analysis
          run: |
            cpplint $(find . -name \*.h -or -name \*.cpp | grep -vE "^\.\/build\/")

